#!env ruby

class Greprb
  def initialize(argv, output, input)
    @argv, @output, @input = argv, output, input
  end

  def exec
    regex = Regexp.compile(@argv)
    @input.each do |line|
      match = regex.match(line)
      case
      when match.nil?
        # do nothing
      when match[1]
        @output.puts match[1]
      when match
        @output.puts match[0]
      end
    end
  end
end

if __FILE__ == $PROGRAM_NAME
  Greprb.new(ARGV[0], $stdout, $stdin).exec
end
